// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxOm9WWsAeIJlPnQJio95BGwfJFwt8Q3E',
    appId: '1:2092545885:android:fadd66d2c04f8c5fc35ab4',
    messagingSenderId: '2092545885',
    projectId: 'pss-security-f6aa8',
    storageBucket: 'pss-security-f6aa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfgNEsCF0FKJAeYG1HK7GFonEKXVgUgaA',
    appId: '1:2092545885:ios:bb7d7d340d314fadc35ab4',
    messagingSenderId: '2092545885',
    projectId: 'pss-security-f6aa8',
    storageBucket: 'pss-security-f6aa8.firebasestorage.app',
    iosBundleId: 'com.example.pss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiuhSggmQ8FpwOPmKKtWiN6SopcUECp-w',
    appId: '1:2092545885:web:1141f8e97074501cc35ab4',
    messagingSenderId: '2092545885',
    projectId: 'pss-security-f6aa8',
    authDomain: 'pss-security-f6aa8.firebaseapp.com',
    storageBucket: 'pss-security-f6aa8.firebasestorage.app',
    measurementId: 'G-1C3BXRXE7J',
  );
}